In [82]:
import pandas as pd

Read WeRateDogs Twitter archive data from a given file to panda dataframe

In [83]:
df_archive = pd.read_csv('twitter-archive-enhanced.csv')

In [84]:
# Check the dataframe
df_archive.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

Download The tweet image predictions data from the internet (URL)

In [85]:
import requests
import os

In [86]:
url = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
response = requests.get(url)

In [87]:
with open(url.split('/')[-1], mode = 'wb') as file:
    file.write(response.content)

Read the downloaded file content and save it in a panda's dataframe

In [88]:
df_prediction = pd.read_csv('image-predictions.tsv',sep='\t')

# Check the dataframe 
df_prediction.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

Use Twitter API to query for each tweet's JSON data using Python's Tweepy library <br>
Store tweet's JSON data is in a tweet-json.txt file <br>
The code below shows how this could be done for those who have twitter developer account <br>
Since I don't, I include this code as a comment so others can use it, and use the tweet-json.txt file 
provided by Udacity.

In [89]:
# import tweepy
# from tweepy import OAuthHandler
# import json
# from timeit import default_timer as timer

# # Query Twitter API for each tweet in the Twitter archive and save JSON in a text file
# # These are hidden to comply with Twitter's API terms and conditions
# consumer_key = 'HIDDEN'
# consumer_secret = 'HIDDEN'
# access_token = 'HIDDEN'
# access_secret = 'HIDDEN'

# auth = OAuthHandler(consumer_key, consumer_secret)
# auth.set_access_token(access_token, access_secret)

# api = tweepy.API(auth, wait_on_rate_limit=True)

# # NOTE TO STUDENT WITH MOBILE VERIFICATION ISSUES:
# # df_1 is a DataFrame with the twitter_archive_enhanced.csv file. You may have to
# # change line 17 to match the name of your DataFrame with twitter_archive_enhanced.csv
# # NOTE TO REVIEWER: this student had mobile verification issues so the following
# # Twitter API code was sent to this student from a Udacity instructor
# # Tweet IDs for which to gather additional data via Twitter's API
# tweet_ids = df_1.tweet_id.values
# len(tweet_ids)

# # Query Twitter's API for JSON data for each tweet ID in the Twitter archive
# count = 0
# fails_dict = {}
# start = timer()
# # Save each tweet's returned JSON as a new line in a .txt file
# with open('tweet_json.txt', 'w') as outfile:
#     # This loop will likely take 20-30 minutes to run because of Twitter's rate limit
#     for tweet_id in tweet_ids:
#         count += 1
#         print(str(count) + ": " + str(tweet_id))
#         try:
#             tweet = api.get_status(tweet_id, tweet_mode='extended')
#             print("Success")
#             json.dump(tweet._json, outfile)
#             outfile.write('\n')
#         except tweepy.TweepError as e:
#             print("Fail")
#             fails_dict[tweet_id] = e
#             pass
# end = timer()
# print(end - start)
# print(fails_dict)

Open tweet-json.txt file and print one line in a readble format to know the desired attribute's names

In [98]:
import json 
import pprint 
import pandas as pd

hashtag_list = []
with open('tweet-json.txt', 'r') as file:
    data = file.readline()
    json_data = json.loads(data)
    pprint.pprint(json_data)
#     if (len(json_data['entities']['hashtags']) > 0) :
#         #print(json_data['entities']['hashtags'][0]['text'])
#         hashtag_list.append(json_data['entities']['hashtags'][0]['text'])

# pd.DataFrame(hashtag_list).nunique()

{'contributors': None,
 'coordinates': None,
 'created_at': 'Tue Aug 01 16:23:56 +0000 2017',
 'display_text_range': [0, 85],
 'entities': {'hashtags': [],
              'media': [{'display_url': 'pic.twitter.com/MgUWQ76dJU',
                         'expanded_url': 'https://twitter.com/dog_rates/status/892420643555336193/photo/1',
                         'id': 892420639486877696,
                         'id_str': '892420639486877696',
                         'indices': [86, 109],
                         'media_url': 'http://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
                         'media_url_https': 'https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
                         'sizes': {'large': {'h': 528,
                                             'resize': 'fit',
                                             'w': 540},
                                   'medium': {'h': 528,
                                              'resize': 'fit',
                                              'w': 540},
                                   'small': {'h': 528,
                                             'resize': 'fit',
                                             'w': 540},
                                   'thumb': {'h': 150,
                                             'resize': 'crop',
                                             'w': 150}},
                         'type': 'photo',
                         'url': 'https://t.co/MgUWQ76dJU'}],
              'symbols': [],
              'urls': [],
              'user_mentions': []},
 'extended_entities': {'media': [{'display_url': 'pic.twitter.com/MgUWQ76dJU',
                                  'expanded_url': 'https://twitter.com/dog_rates/status/892420643555336193/photo/1',
                                  'id': 892420639486877696,
                                  'id_str': '892420639486877696',
                                  'indices': [86, 109],
                                  'media_url': 'http://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
                                  'media_url_https': 'https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
                                  'sizes': {'large': {'h': 528,
                                                      'resize': 'fit',
                                                      'w': 540},
                                            'medium': {'h': 528,
                                                       'resize': 'fit',
                                                       'w': 540},
                                            'small': {'h': 528,
                                                      'resize': 'fit',
                                                      'w': 540},
                                            'thumb': {'h': 150,
                                                      'resize': 'crop',
                                                      'w': 150}},
                                  'type': 'photo',
                                  'url': 'https://t.co/MgUWQ76dJU'}]},
 'favorite_count': 39467,
 'favorited': False,
 'full_text': "This is Phineas. He's a mystical boy. Only ever appears in the "
              'hole of a donut. 13/10 https://t.co/MgUWQ76dJU',
 'geo': None,
 'id': 892420643555336193,
 'id_str': '892420643555336193',
 'in_reply_to_screen_name': None,
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'is_quote_status': False,
 'lang': 'en',
 'place': None,
 'possibly_sensitive': False,
 'possibly_sensitive_appealable': False,
 'retweet_count': 8853,
 'retweeted': False,
 'source': '<a href="http://twitter.com/download/iphone" '
           'rel="nofollow">Twitter for iPhone</a>',
 'truncated': False,
 'user': {'contributors_enabled': False,
          'created_at': 'Sun Nov 15 21:41:29 +0000 2015',
          'default_profile': False,
          'default_profile_image': False,
          'description': '#1 Source for Professional Dog Ratings | STORE: '
                         '@ShopWeRateDogs | IG, FB & SC: WeRateDogs MOBILE '
                         'APP: @GoodDogsGame | Business: '
                         'dogratingtwitter@gmail.com',
          'entities': {'description': {'urls': []},
                       'url': {'urls': [{'display_url': 'weratedogs.com',
                                         'expanded_url': 'http://weratedogs.com',
                                         'indices': [0, 23],
                                         'url': 'https://t.co/N7sNNHAEXS'}]}},
          'favourites_count': 114031,
          'follow_request_sent': False,
          'followers_count': 3200889,
          'following': True,
          'friends_count': 104,
          'geo_enabled': True,
          'has_extended_profile': True,
          'id': 4196983835,
          'id_str': '4196983835',
          'is_translation_enabled': False,
          'is_translator': False,
          'lang': 'en',
          'listed_count': 2784,
          'location': 'DM YOUR DOGS, WE WILL RATE',
          'name': 'WeRateDogs™ (author)',
          'notifications': False,
          'profile_background_color': '000000',
          'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
          'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
          'profile_background_tile': False,
          'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4196983835/1501129017',
          'profile_image_url': 'http://pbs.twimg.com/profile_images/861415328504569856/R2xOOfwe_normal.jpg',
          'profile_image_url_https': 'https://pbs.twimg.com/profile_images/861415328504569856/R2xOOfwe_normal.jpg',
          'profile_link_color': 'F5ABB5',
          'profile_sidebar_border_color': '000000',
          'profile_sidebar_fill_color': '000000',
          'profile_text_color': '000000',
          'profile_use_background_image': False,
          'protected': False,
          'screen_name': 'dog_rates',
          'statuses_count': 5288,
          'time_zone': None,
          'translator_type': 'none',
          'url': 'https://t.co/N7sNNHAEXS',
          'utc_offset': None,
          'verified': True}}

In [91]:
#This function computes the number of lines in a file
def rawcount(filename):
    f = open(filename, 'rb')
    lines = 0
    buf_size = 1024 * 1024
    read_f = f.raw.read

    buf = read_f(buf_size)
    while buf:
        lines += buf.count(b'\n')
        buf = read_f(buf_size)

    return lines

In [109]:
# Count the number of lines. Thst is, the number of tweets, as each line represents one tweet info.
linesCount = rawcount('tweet-json.txt')

# Store tweet's info in retweet_info array, to be converted later into panda's dataframe
retweet_info = []

with open('tweet-json.txt', 'r') as file:
    #For each line (tweet) get and store the info.
    for i in range (linesCount):
        data = file.readline()
        json_data = json.loads(data)
        id = json_data['id']
        retweet_count = json_data['retweet_count']
        favorite_count = json_data['favorite_count']
        created_at = json_data['created_at']
        num_of_hashtag = len(json_data['entities']['hashtags'])
        hashtag_list = []
        for j in range (hashtag_length):
            hashtag_list.append(json_data['entities']['hashtags'][j]['text'])
        followers_count = json_data['user']['followers_count']
        
        retweet_info.append({
            'id': id,
            'retweet_count': retweet_count,
            'favorite_count': favorite_count,
            'num_of_hashtag': num_of_hashtag,
            'hashtag_list': hashtag_list,
            'followers_count': followers_count
        })
 
df_retweet_info = pd.DataFrame(retweet_info)

In [110]:
df_retweet_info.head(10)

,id,retweet_count,favorite_count,num_of_hashtag,hashtag_list,followers_count
0,892420643555336193,8853,39467,0,[],3200889
1,892177421306343426,6514,33819,0,[],3200889
2,891815181378084864,4328,25461,0,[],3200889
3,891689557279858688,8964,42908,0,[],3200889
4,891327558926688256,9774,41048,1,[],3200889
5,891087950875897856,3261,20562,1,[],3200889
6,890971913173991426,2158,12041,0,[],3200889
7,890729181411237888,16716,56848,0,[],3200889
8,890609185150312448,4429,28226,1,[],3200889
9,890240255349198849,7711,32467,0,[],3200889